src/Entity/Author.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AuthorRepository")
 */
class Author
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Firstname;

    /**
     * @ORM\Column(type="datetime")
     */
    private $BirthDate;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $DeathDate;

    /**
     * @ORM\Column(type="text")
     */
    private $biographie;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getBirthDate(): ?\DateTimeInterface
    {
        return $this->BirthDate;
    }

    public function setBirthDate(\DateTimeInterface $BirthDate): self
    {
        $this->BirthDate = $BirthDate;

        return $this;
    }

    public function getDeathDate(): ?\DateTimeInterface
    {
        return $this->DeathDate;
    }

    public function setDeathDate(?\DateTimeInterface $DeathDate): self
    {
        $this->DeathDate = $DeathDate;

        return $this;
    }

    public function getBiographie(): ?string
    {
        return $this->biographie;
    }

    public function setBiographie(string $biographie): self
    {
        $this->biographie = $biographie;

        return $this;
    }
}

templates/author.html.twig
{% extends 'base.html.twig' %}

{% block title_author %}Nos livres{% endblock %}

{% block section %}

{% for author in author %}
    <p class="box_author">
        <span>{{ author.name }} {{ author.firstname }}</span><br>
        <strong>Née le :</strong> {{ author.birthdate | date("m/d/Y") }}

            {% if author.deathDate == true %}
                <br><strong>Mort le :</strong>{{ author.DeathDate | date("m/d/Y") }}
            {%  endif %}

        <a href="{{ path('author_delete', {'id': author.id}) }}" class="case">Supprimer</a>
        <a href="{{ path('author_update', {'id': author.id}) }}" class="modifier">Modifier Prénom</a>

    </p>
{% endfor %}

</div>
{% endblock %}

templates/author.recuSQL.html.twig
{% extends 'base.html.twig' %}

{% block section %}

    <div>
        <p>Requete enregistré dans la base de donné "Library"</p>
        <span>Prénom et Nom de l'autheur : {{ author.firstname }} {{ author.name }}</span><br>
        <span>Année de naissance : {{ author.birthDate | date('d/m/Y')}}</span><br>
        <span>Biographie : {{ author.biographie }}</span><br>
    </div>

{% endblock %}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Ma bibliothèque{% endblock %}</title>
        <link rel="stylesheet" href="{{ asset('css/style.css') }}">
    </head>
    <body>

    <header>
        <div class="box_header">
            <h1 class="titre">Ma bibliotèque</h1>
            <nav>
                <label for="site-search">Recherche :</label>
                <input type="search" id="site-search" name="q"
                       aria-label="mot clef">
                <button>Recherche</button>

                <a href="{{ path('author_list') }}">{% block title_book %}{% endblock %}</a>
                <a href="{{ path('book_list') }}">{% block title_author %}{% endblock %}</a>
            </nav>
        </div>
    </header>

    <main>
        <div class="book">
            {% block section %}{% endblock %}
        </div>
    </main>

    <footer>
        <div class="box_footer">
            <span>Author</span>
            <span>Book</span>
            <span>Blanche neige</span>
        </div>
    </footer>
    </body>
</html>

templates/book.html.twig
{% extends 'base.html.twig' %}

{% block title_book %}Nos autheurs{% endblock %}

{% block section %}

    {% for book in book %}

        <div class="big_box">
            <div class="box">
                <p class="box_book">
                    <a href="{{ path('book', {'id': book.id} ) }}">{{ book.title }}</a>
                    : {{ book.nbpages }} pages. <br>
                    Catégorie :{{ book.style}} <br>

                    {% if book.stock == 1 %}
                        <span class="color_dispo">Le livre est disponible</span>
                    {% else %}
                        <span class="color_noDispo">Non disponible</span>
                    {% endif %}
                </p>
            </div>
            <div class="box">
                <a href="{{ path('book_delete', {'id': book.id}) }}" class="case">Supprimer</a>
                <a href="{{ path('book_update', {'id': book.id}) }}" class="modifier">Modifier le titre</a>
                <a href="{{ path('book_update_form', {'id': book.id}) }}" class="modif">Modifier le livre</a>
            </div>
        </div>

    {% endfor %}

    </div>
{% endblock %}

templates/book.show.html.twig
{% extends 'base.html.twig' %}

{% block section %}

        <p class="box_book">

            {{ bookShow.title }} : {{ bookShow.nbpages }} pages. <br><strong>Catégorie :</strong>{{ bookShow.style}}

        </p>

    </div>
{% endblock %}

templates/book_form.html.twig
{# je crée le html de mon formulaire (balise form, input etc) en utilisant la fonction
 form() avec en parametre ma variable de formulaire  #}
{% extends 'base.html.twig' %}

{% block section %}

<div class="form">
    {{ form(bookFormView) }}
</div>

{% endblock %}

templates/finder.authors.html.twig
{% extends 'base.html.twig' %}


{% block section %}

    {% for author in author %}

        {{ author.biographie | raw}}

    {% endfor %}

{% endblock %}

templates/recuSQL.html.twig
{% extends 'base.html.twig' %}

{% block section %}

    <div>
        <p>Requete enregistré dans la base de donné "Library"</p>
        <span>Titre du livre : {{ book.title }}</span><br>
        <span>Genre : {{ book.style }}</span><br>
        <span>Nombre de pages : {{ book.nbpages }}</span><br>
        <sapn>Disponibilité : {{ book.stock }}</sapn>
    </div>

{% endblock %}

templates/show_book.html.twig
{% extends 'base.html.twig' %}

{% block section %}

    <article>

        <div class="box_book"><h2>{{ book.title }}</h2> : {{ book.nbpages }} pages. <br>Catégorie :{{ book.style}}  </div>

    </article>

    </div>
{% endblock %}